version: '3'
name: edgecontributor-3
services:
  mongodb3:
    image: mongo:latest
    container_name: mongodb3
    hostname: mongodb
    restart: unless-stopped
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes: 
      - mongoDB-data3:/data/db
      - mongoDB-config3:/data/configdb
    networks:
      - mobileapplication3

  mongo-express3:
    image: mongo-express:latest
    container_name: mongo-express3
    hostname: mongo-express
    restart: unless-stopped
    ports:
      - 8063:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb3
    networks:
      - mobileapplication3

  camel3:
    container_name: camel3
    build:
      context: ./middleware
    hostname: camel
    ports:
      - 8032:8030
    networks:
      - mobileapplication3
    depends_on:
      - mongodb3
      - datasynthesizer3
      - edge-contributor-3
      - machinelearning3
  
  datasynthesizer3:
    build:
      context: ./datasynthesizer
    container_name: datasynthesizer3
    hostname: datasynthesizer
    restart: unless-stopped
    networks:
      - mobileapplication3
    depends_on:
      - mongodb3

  machinelearning3:
    build:
      context: ./machinelearningmodel
    container_name: machinelearning3
    hostname: machinelearning
    restart: unless-stopped
    networks:
      - mobileapplication3

  postgres-edge-contributor-3:
    image: postgres:13
    container_name: 'postgres-edge-contributor-3'
    hostname: postgres-edge-contributor-3
    ports:
      - "5443:5432"
    env_file:
      - ./DataspaceConnector/postgres-edge-contributor-3.env
    networks:
      - mobileapplication3
    volumes:
     - edge-contributor-3:/var/lib/postgresql/data

  edge-contributor-3:
    build:
      context: ./DataspaceConnector
    container_name: 'edge-contributor-3'
    hostname: edge-contributor
    ports:
      - 8083:8080
    env_file:
      - ./DataspaceConnector/edge-contributor-3.env
    environment:
      - SERVER_SSL_ENABLED=false
    networks:
      - mobileapplication3
    depends_on:
      - postgres-edge-contributor-3

  edge-contributor-ui-3:
    build:
      context: ./DataspaceConnector/DataspaceConnector-UI
    container_name: 'edge-contributor-ui-3'
    hostname: edge-contributor-ui
    environment:
      - CONNECTOR_URL=http://edge-contributor:8080
      - CONNECTOR_USER=admin
      - CONNECTOR_PASSWORD=password
    ports:
      - "8093:8083"
    networks:
      - mobileapplication3
    depends_on:
      - edge-contributor-3
    
  webframework3:
    build:
      context: ./webframework
    hostname: webframework
    ports:
      - "82:80"
    environment:
      - NODE_ENV=production
    restart: on-failure
    networks:
      - mobileapplication3
    depends_on:
      - camel3

networks:
  mobileapplication3:

volumes:
  mongoDB-data3: {}
  mongoDB-config3: {}
  edge-contributor-3: {}
